<?php

declare(strict_types=1);

namespace App\Auth;

/**
 * Client addresses that get the package files without credentials. Stored in
 * ip-allow-list.json next to the htpasswd file and rendered to ip-allow-list.conf,
 * an nginx snippet with "allow" rules that satis-panel-serve reloads nginx for.
 */
final class IpAllowList
{
    public const LABEL_PATTERN = '/^[\w .@+-]{0,64}$/u';

    private readonly string $file;
    private readonly string $nginxFile;

    public function __construct(string $htpasswdFile)
    {
        $this->file = dirname($htpasswdFile).'/ip-allow-list.json';
        $this->nginxFile = dirname($htpasswdFile).'/ip-allow-list.conf';
    }

    public function path(): string
    {
        return $this->file;
    }

    public function nginxPath(): string
    {
        return $this->nginxFile;
    }

    /**
     * @return list<array{id: string, ip: string, label: string, created_at: string}>
     */
    public function all(): array
    {
        $entries = array_values($this->read());
        usort($entries, static fn (array $a, array $b): int => strcmp($a['created_at'], $b['created_at']));

        return $entries;
    }

    /**
     * @return array{id: string, ip: string, label: string, created_at: string}
     */
    public function add(string $ip, string $label = ''): array
    {
        $ip = self::normalize($ip);
        $label = trim($label);
        if (!preg_match(self::LABEL_PATTERN, $label)) {
            throw new \InvalidArgumentException('Invalid label.');
        }
        $entries = $this->read();
        foreach ($entries as $entry) {
            if ($entry['ip'] === $ip) {
                throw new \InvalidArgumentException(sprintf('%s is already on the list.', $ip));
            }
        }
        $entry = [
            'id' => bin2hex(random_bytes(6)),
            'ip' => $ip,
            'label' => $label,
            'created_at' => (new \DateTimeImmutable())->format(\DateTimeInterface::ATOM),
        ];
        $entries[$entry['id']] = $entry;
        $this->write($entries);

        return $entry;
    }

    public function remove(string $id): void
    {
        $entries = $this->read();
        unset($entries[$id]);
        $this->write($entries);
    }

    /**
     * Accepts an IPv4/IPv6 address or CIDR range and returns it in canonical form.
     *
     * @throws \InvalidArgumentException
     */
    public static function normalize(string $value): string
    {
        $value = trim($value);
        [$address, $prefix] = array_pad(explode('/', $value, 2), 2, null);
        $address = trim((string) $address);
        $binary = @inet_pton($address);
        if (false === $binary) {
            throw new \InvalidArgumentException(sprintf('"%s" is not a valid IP address or CIDR range.', $value));
        }
        $bits = 4 === strlen($binary) ? 32 : 128;
        $address = (string) inet_ntop($binary);
        if (null === $prefix) {
            return $address;
        }
        if (!ctype_digit($prefix) || (int) $prefix > $bits) {
            throw new \InvalidArgumentException(sprintf('"%s" is not a valid CIDR range (prefix 0-%d).', $value, $bits));
        }

        return $address.'/'.(int) $prefix;
    }

    /**
     * @return array<string, array{id: string, ip: string, label: string, created_at: string}>
     */
    private function read(): array
    {
        if (!is_file($this->file)) {
            return [];
        }
        $data = json_decode((string) file_get_contents($this->file), true);
        if (!is_array($data)) {
            return [];
        }
        $entries = [];
        foreach ($data as $id => $entry) {
            if (is_array($entry) && is_string($entry['ip'] ?? null)) {
                $entries[(string) $id] = [
                    'id' => (string) $id,
                    'ip' => $entry['ip'],
                    'label' => (string) ($entry['label'] ?? ''),
                    'created_at' => (string) ($entry['created_at'] ?? ''),
                ];
            }
        }

        return $entries;
    }

    /**
     * @param array<string, array{id: string, ip: string, label: string, created_at: string}> $entries
     */
    private function write(array $entries): void
    {
        $dir = dirname($this->file);
        if (!is_dir($dir) && !@mkdir($dir, 0775, true) && !is_dir($dir)) {
            throw new \RuntimeException(sprintf('Cannot create %s.', $dir));
        }
        $this->replace($this->file, json_encode((object) $entries, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)."\n", 0600);

        $nginx = "# Generated by Satis Panel, edit the list under Composer access.\n";
        foreach ($entries as $entry) {
            $nginx .= sprintf("allow %s;%s\n", $entry['ip'], '' !== $entry['label'] ? ' # '.$entry['label'] : '');
        }
        if ([] !== $entries) {
            $nginx .= "deny all;\n";
        }
        $this->replace($this->nginxFile, $nginx, 0644);
    }

    private function replace(string $file, string $content, int $mode): void
    {
        $tmp = $file.'.tmp';
        if (false === file_put_contents($tmp, $content, LOCK_EX)) {
            throw new \RuntimeException(sprintf('Cannot write %s.', $file));
        }
        chmod($tmp, $mode);
        HtpasswdManager::keepOwnership($file, $tmp);
        if (!rename($tmp, $file)) {
            @unlink($tmp);
            throw new \RuntimeException(sprintf('Cannot write %s.', $file));
        }
    }
}
